### PR TITLE
Use `cacert.pem` from certifi 2024.7.4.

### PR DESCRIPTION
**Pull request by jsirois**
Add `nox -e update-certifi-cacert-pem` and run it to refresh Pip's
vendored certifi with the latest CA certs that should be trusted.

CF #12 by @gs-kamnas that prompted this.

### CODE REVIEW

**Comment by gs-kamnas** [comment]
This looks reasonable from an implementation and security standpoint as well. Valid point with regards to compatibility limitations with older python interpreter versions in my implementation in #12.

**Comment by jsirois** [comment]
@gs-kamnas thanks for prompting this long overdue refresh. I'm sorry I didn't notice your PR until just a few days ago! Pex vendored this old Pip a good while ago and so I ~never look back here, but was prompted by the fix for statically compiled CPython support.

@benjyw I've tested this out over in a Pex branch and the comment I add at the top of the cacert.pem causes no issues; so I'll submit and fire up a Pex change to get out this security fix.

**Comment by gs-kamnas** [comment]
Appears that the testsuite also requires making calls to Git as part of execution.

Therefore https://github.com/pex-tool/pip/compare/certifi/refresh-cacert.pem...gs-kamnas:pex-pip:certifi/refresh-cacert.pem may help with a few of the testcases that are presently failing.

**Comment by jsirois** [comment]
@gs-kamnas - yeah - these are the Pip projects CI setups which I haven't tried to get / keep working in the fork. My ground truth CI for any edits I make in this branch are back in pex-tool/pex where it heavily exercises Pip 20.3.4+patched (its vendored Pip that comes from this branch).

**Comment by jsirois** [comment]
Ok, this is being used in https://github.com/pex-tool/pex/pull/2476

**Pull request merged**
