### PR TITLE
Cache parse_links() by --find-links html page content 

### LINKED ISSUE #887: the pip-powered resolve in pex 2 will re-tokenize --find-links pages on each transitive requirement
We've been running into an issue when trying to test the feature in pantsbuild/pants#8793 (inspired by #789) with pex versions later than 2. When the vendored pip resolver fetches html pages provided as `--find-links` arguments, it appears to always fetch with the `cachecontrol` header `max-age: 0`, which appears to mean it always re-fetches and re-tokenizes every `--find-links` html page every time it tries to resolve any requirement. This leads to extremely long resolve times when resolving against a large remote `--find-links` html page in pex 2 (12 minutes vs 1.5 minutes for a particular intransitive resolve).

Application of the `max-age` header: https://github.com/pantsbuild/pex/blob/e078b88659b2992c839c110ca3447f64e6838f08/pex/vendor/_vendored/pip/pip/_internal/index/collector.py#L130-L143

Output excerpt with `-vvvvvvvvv`:
```
Fetching project page and analyzing links: https://INTERNAL-URL.com/INTERNAL-FIND-LINKS-REPO
  Getting page https://INTERNAL-URL.com/INTERNAL-FIND-LINKS-REPO
  Looking up "https://INTERNAL-URL.com/INTERNAL-FIND-LINKS-REPO" in the cache
  Request header has "max_age" as 0, cache bypassed
  Resetting dropped connection: INTERNAL-URL.com
  https://INTERNAL-URL.com:443 "GET /INTERNAL-FIND-LINKS-REPO HTTP/1.1" 200 858
  Updating cache with response from "https://INTERNAL-URL.com/INTERNAL-FIND-LINKS-REPO"
```

Size of our large `--find-links` page (when saved to disk):
```bash
> wc -c wow.html
1577275 wow.html
```

Will try to post a repro if possible which avoids dumping our internal repo into a public issue. Note that pex 1 does not appear to support local fileystem paths to html pages with `--find-links`, so `--find-links=wow.html` in pex 2 is not directly comparable to the result in pex 1.

### PR DESCRIPTION
**Pull request by cosmicexplorer**
Cherry-pick of pypa/pip#7729! This change is intended to fix pantsbuild/pex#887.

### CODE REVIEW

**Review by benjyw — APPROVED** [review]
I see, so you're not trying to cache between runs, just within a single run. 

Would there be even more benefit in the future to caching between runs?

**Comment by cosmicexplorer** [comment]
> Would there be even more benefit in the future to caching between runs?

*EDITED THIS COMMENT A LOT!!*

See maybe-related convo over at the pip PR in https://github.com/pypa/pip/pull/7729#issuecomment-585590467.

pypa/pip#5670 is working against us a little here, because we don't want to have caching that avoids reading in updates from publishing. I'm actually not sure if I can see an obvious form of caching between runs that improves on this PR without causing issues like pypa/pip#5670.

**Comment by cosmicexplorer** [comment]
Hm, I think the above is correct, but *also* think a really relevant optimization would be to cache the html page fetching as well for `--find-links` repos (currently the page is still re-fetched on each transitive requirement -- this caching just avoids re-parsing the page constantly). That would probably take the shape of another dictionary somewhere nearby to avoid fetching an `HTMLPage` more than once, keyed by url. I'll use the same benchmark script as in pypa/pip#7729 to see whether that change affects performance too.

**Comment by cosmicexplorer** [comment]
...even locally (without going across the network to retrieve the `--find-links` page), it appears that caching the html page itself by url has an impact on performance. Via the benchmark script at pypa/pip#7729, I'm seeing pip complete at pretty reliably 11.8 seconds with the changes in 1d8f381, and 11.9-12.+ seconds with just the parse_links() caching. I'm going to propose adding this additional level of caching to the upstream pip PR as well.

**Comment by cosmicexplorer** [comment]
Proposed the change in the upstream pip PR: https://github.com/pypa/pip/pull/7729#issuecomment-586028550.

**Comment by cosmicexplorer** [comment]
(we will be cherry-picking the resulting changes from pypa/pip#7729, if they differ from this, after it is approved and merged!)

**Pull request merged**
