### PR TITLE
Support multiple platforms.

### PR DESCRIPTION
**Pull request by jsirois**
Allow multiple --platform arguments to support downloading wheels for
manylinux* and linux when it's known out of band that this is safe.

### CODE REVIEW

**Comment by jsirois** [comment]
N.B.: This PR will form the basis of an issue/PR against pypa/pip to include support for more foreign download scenarios fr solving https://github.com/pantsbuild/pex/issues/823 and like issues. Notably missing are new tests, a NEWS entry and some doc updates.

**Comment by jsirois** [comment]
Reviewers - I'm going to submit this TBR to base a pex PR off it. Feedback is welcome though. As noted above, a bit of polish is needed to turn this into an upstream issue/PR.

**Review by benjyw — COMMENTED** [review]
Looks good to me from a code perspective. I don't have a sense of how much polish this might need in order to get upstreamed, but the code changes are fairly clear and justifiable.  The only thing that might be worth calling out to upstream reviewers is why `version_info_to_nodot` is no longer needed, as it's not immediately obvious.

**Comment by luislew** [comment]
👋 @jsirois any updates on filing a PR back to `pip` to adopt this feature for `pip download`?

**Pull request merged**
